version: 2
updates:
  # Monitor all dependencies (requirements.txt and requirements-dev.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Perth"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "eben71"
    labels:
      - "dependencies"
      - "python"
      - "dev-tools"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      include: "scope"
    description: "Updates for all dependencies (production and development)"