version: 2
updates:
  # Monitor Python dependencies (requirements.txt and requirements-dev.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Perth"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    reviewers:
      - "eben71"  # Your GitHub username
    labels:
      - "dependencies"
      - "python"
      - "dev-tools"
    patterns:
      - "requirements.txt"      # Production dependencies
      - "requirements-dev.txt"  # Development dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Ignore major version updates