version: 2
updates:
  # Monitor production dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Perth"
    target-branch: "dependencies-prod"
    open-pull-requests-limit: 5
    reviewers:
      - "eben71"  # Your GitHub username
    labels:
      - "dependencies"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Ignore major version updates
    commit-message:
      prefix: "deps(prod)"
      include: "scope"
    description: "Updates for production dependencies in requirements.txt"

  # Monitor development dependencies (requirements-dev.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Perth"
    target-branch: "dependencies-dev"
    open-pull-requests-limit: 5
    reviewers:
      - "eben71"  # Your GitHub username
    labels:
      - "dependencies"
      - "dev-tools"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Ignore major version updates
    commit-message:
      prefix: "deps(dev)"
      include: "scope"
    description: "Updates for development dependencies in requirements-dev.txt"