# mcr.microsoft.com/playwright/python
# https://mcr.microsoft.com/en-us/artifact/mar/playwright/python
# https://github.com/microsoft/playwright-python/releases
FROM mcr.microsoft.com/playwright/python:v1.53.0

WORKDIR /app

# Copy dependency files
COPY requirements.txt .
RUN pip install -r requirements.txt

ENV PYTHONPATH=/app

CMD ["uvicorn", "frontend.main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]