FROM python:3.12-slim

WORKDIR /app

# Copy dependency files
COPY requirements.txt .
RUN pip install -r requirements.txt

ENV PYTHONPATH=/app

CMD ["uvicorn", "frontend.main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]