FROM python:3.12-slim

WORKDIR /app

COPY ./frontend ./frontend
RUN pip install --upgrade pip && pip install --no-cache-dir -r frontend/requirements.txt

ENV PYTHONPATH=/app

CMD ["uvicorn", "frontend.main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]