name: CI

on:
  pull_request:
  push:
    branches: [ main ]

# Cancel superseded runs on the same ref
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: 🔍 Pre‑commit checks (lint, format, secrets)
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - uses: ./.github/actions/python-setup
      with:
        python-version: "3.12"

    - name: List package versions
      run: pip list

    - name: Run pre-commit
      run: |
        pip install pre-commit detect-secrets
        pre-commit run --all-files --show-diff-on-failure

  unit-tests:
    name: 🧪 Unit tests + coverage
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - uses: ./.github/actions/python-setup
      with:
        python-version: "3.12"

    - name: Generate ENCRYPTION_KEY for unit tests
      run: |
        python - <<'PY' >> $GITHUB_ENV
        from cryptography.fernet import Fernet
        print("ENCRYPTION_KEY=" + Fernet.generate_key().decode())
        PY

    - name: Run unit tests + lint/mypy (Makefile)
      run: make ci

    - name: Upload coverage.xml
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: coverage.xml
        if-no-files-found: ignore
