name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install pre-commit detect-secrets
      - run: pre-commit run detect-secrets --all-files --hook-stage manual
